# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

beta_reassign_core <- function(probs, vaf_index, unique_vaf, freq) {
    .Call(`_TEATIME_beta_reassign_core`, probs, vaf_index, unique_vaf, freq)
}

dbeta_matrix_cpp <- function(x, a, b) {
    .Call(`_TEATIME_dbeta_matrix_cpp`, x, a, b)
}

wilcox_test_p_asym <- function(x, y) {
    .Call(`_TEATIME_wilcox_test_p_asym`, x, y)
}

